[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"

# Environment variables (you'll need to set these in Netlify dashboard)
# DATABASE_URL = "your-neon-connection-string"
# NODE_ENV = "production"